# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black --check .
        language: system
        types: [python]
        pass_filenames: false
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: poetry run flake8 .
        language: system
        types: [python]
        pass_filenames: false
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: poetry run mypy .
        language: system
        types: [python]
        pass_filenames: false
  - repo: local
    hooks:
      - id: tests
        name: tests
        entry: poetry run coverage run -m pytest
        language: system
        types: [python]
        pass_filenames: false
  - repo: local
    hooks:
      - id: coverage
        name: coverage
        entry: poetry run coverage report
        language: system
        types: [python]
        pass_filenames: false
