# generated by datamodel-codegen:
#   filename:  get_quote_response.json
#   timestamp: 2022-12-29T00:24:07+00:00

from __future__ import annotations

from typing import Dict, Optional, Union

from pydantic import BaseModel, Field
from typing_extensions import Literal


class MutualFundQuote(BaseModel):
    assetType: Optional[Literal['MUTUAL_FUND']] = None
    symbol: Optional[str] = None
    description: Optional[str] = None
    closePrice: Optional[float] = None
    netChange: Optional[float] = None
    totalVolume: Optional[int] = None
    tradeTimeInLong: Optional[int] = None
    exchange: Optional[str] = None
    exchangeName: Optional[str] = None
    digits: Optional[int] = None
    field_52WkHigh: Optional[float] = Field(None, alias='52WkHigh')
    field_52WkLow: Optional[float] = Field(None, alias='52WkLow')
    nAV: Optional[float] = None
    peRatio: Optional[float] = None
    divAmount: Optional[float] = None
    divYield: Optional[float] = None
    divDate: Optional[str] = None
    securityStatus: Optional[str] = None


class FutureQuote(BaseModel):
    assetType: Optional[Literal['FUTURE']] = None
    symbol: Optional[str] = None
    bidPriceInDouble: Optional[float] = None
    askPriceInDouble: Optional[float] = None
    lastPriceInDouble: Optional[float] = None
    bidId: Optional[str] = None
    askId: Optional[str] = None
    highPriceInDouble: Optional[float] = None
    lowPriceInDouble: Optional[float] = None
    closePriceInDouble: Optional[float] = None
    exchange: Optional[str] = None
    description: Optional[str] = None
    lastId: Optional[str] = None
    openPriceInDouble: Optional[float] = None
    changeInDouble: Optional[float] = None
    futurePercentChange: Optional[float] = None
    exchangeName: Optional[str] = None
    securityStatus: Optional[str] = None
    openInterest: Optional[float] = None
    mark: Optional[float] = None
    tick: Optional[float] = None
    tickAmount: Optional[float] = None
    product: Optional[str] = None
    futurePriceFormat: Optional[str] = None
    futureTradingHours: Optional[str] = None
    futureIsTradable: Optional[bool] = None
    futureMultiplier: Optional[float] = None
    futureIsActive: Optional[bool] = None
    futureSettlementPrice: Optional[float] = None
    futureActiveSymbol: Optional[str] = None
    futureExpirationDate: Optional[str] = None


class FutureOptionQuote(BaseModel):
    assetType: Optional[Literal['OPTION']] = None
    symbol: Optional[str] = None
    bidPriceInDouble: Optional[float] = None
    askPriceInDouble: Optional[float] = None
    lastPriceInDouble: Optional[float] = None
    highPriceInDouble: Optional[float] = None
    lowPriceInDouble: Optional[float] = None
    closePriceInDouble: Optional[float] = None
    description: Optional[str] = None
    openPriceInDouble: Optional[float] = None
    netChangeInDouble: Optional[float] = None
    openInterest: Optional[float] = None
    exchangeName: Optional[str] = None
    securityStatus: Optional[str] = None
    volatility: Optional[float] = None
    moneyIntrinsicValueInDouble: Optional[float] = None
    multiplierInDouble: Optional[float] = None
    digits: Optional[int] = None
    strikePriceInDouble: Optional[float] = None
    contractType: Optional[str] = None
    underlying: Optional[str] = None
    timeValueInDouble: Optional[float] = None
    deltaInDouble: Optional[float] = None
    gammaInDouble: Optional[float] = None
    thetaInDouble: Optional[float] = None
    vegaInDouble: Optional[float] = None
    rhoInDouble: Optional[float] = None
    mark: Optional[float] = None
    tick: Optional[float] = None
    tickAmount: Optional[float] = None
    futureIsTradable: Optional[bool] = None
    futureTradingHours: Optional[str] = None
    futurePercentChange: Optional[float] = None
    futureIsActive: Optional[bool] = None
    futureExpirationDate: Optional[int] = None
    expirationType: Optional[str] = None
    exerciseType: Optional[str] = None
    inTheMoney: Optional[bool] = None


class IndexQuote(BaseModel):
    assetType: Optional[Literal['INDEX']] = None
    symbol: Optional[str] = None
    description: Optional[str] = None
    lastPrice: Optional[float] = None
    openPrice: Optional[float] = None
    highPrice: Optional[float] = None
    lowPrice: Optional[float] = None
    closePrice: Optional[float] = None
    netChange: Optional[float] = None
    totalVolume: Optional[int] = None
    tradeTimeInLong: Optional[int] = None
    exchange: Optional[str] = None
    exchangeName: Optional[str] = None
    digits: Optional[int] = None
    field_52WkHigh: Optional[float] = Field(None, alias='52WkHigh')
    field_52WkLow: Optional[float] = Field(None, alias='52WkLow')
    securityStatus: Optional[str] = None


class OptionQuote(BaseModel):
    assetType: Optional[Literal['OPTION']] = None
    symbol: Optional[str] = None
    description: Optional[str] = None
    bidPrice: Optional[float] = None
    bidSize: Optional[int] = None
    askPrice: Optional[float] = None
    askSize: Optional[int] = None
    lastPrice: Optional[float] = None
    lastSize: Optional[int] = None
    openPrice: Optional[float] = None
    highPrice: Optional[float] = None
    lowPrice: Optional[float] = None
    closePrice: Optional[float] = None
    netChange: Optional[float] = None
    totalVolume: Optional[int] = None
    quoteTimeInLong: Optional[int] = None
    tradeTimeInLong: Optional[int] = None
    mark: Optional[float] = None
    openInterest: Optional[float] = None
    volatility: Optional[float] = None
    moneyIntrinsicValue: Optional[float] = None
    multiplier: Optional[float] = None
    strikePrice: Optional[float] = None
    contractType: Optional[str] = None
    underlying: Optional[str] = None
    timeValue: Optional[float] = None
    deliverables: Optional[str] = None
    delta: Optional[float] = None
    gamma: Optional[float] = None
    theta: Optional[float] = None
    vega: Optional[float] = None
    rho: Optional[float] = None
    securityStatus: Optional[str] = None
    theoreticalOptionValue: Optional[float] = None
    underlyingPrice: Optional[float] = None
    uvExpirationType: Optional[str] = None
    exchange: Optional[str] = None
    exchangeName: Optional[str] = None
    settlementType: Optional[str] = None


class ForexQuote(BaseModel):
    assetType: Optional[Literal['FOREX']] = None
    symbol: Optional[str] = None
    bidPriceInDouble: Optional[float] = None
    askPriceInDouble: Optional[float] = None
    lastPriceInDouble: Optional[float] = None
    highPriceInDouble: Optional[float] = None
    lowPriceInDouble: Optional[float] = None
    closePriceInDouble: Optional[float] = None
    exchange: Optional[str] = None
    description: Optional[str] = None
    openPriceInDouble: Optional[float] = None
    changeInDouble: Optional[float] = None
    percentChange: Optional[float] = None
    exchangeName: Optional[str] = None
    digits: Optional[int] = None
    securityStatus: Optional[str] = None
    tick: Optional[float] = None
    tickAmount: Optional[float] = None
    product: Optional[str] = None
    tradingHours: Optional[str] = None
    isTradable: Optional[bool] = None
    marketMaker: Optional[str] = None
    field_52WkHighInDouble: Optional[float] = Field(None, alias='52WkHighInDouble')
    field_52WkLowInDouble: Optional[float] = Field(None, alias='52WkLowInDouble')
    mark: Optional[float] = None


class ETFQuote(BaseModel):
    assetType: Optional[Literal['ETF']] = None
    symbol: Optional[str] = None
    description: Optional[str] = None
    bidPrice: Optional[float] = None
    bidSize: Optional[int] = None
    bidId: Optional[str] = None
    askPrice: Optional[float] = None
    askSize: Optional[int] = None
    askId: Optional[str] = None
    lastPrice: Optional[float] = None
    lastSize: Optional[int] = None
    lastId: Optional[str] = None
    openPrice: Optional[float] = None
    highPrice: Optional[float] = None
    lowPrice: Optional[float] = None
    closePrice: Optional[float] = None
    netChange: Optional[float] = None
    totalVolume: Optional[int] = None
    quoteTimeInLong: Optional[int] = None
    tradeTimeInLong: Optional[int] = None
    mark: Optional[float] = None
    exchange: Optional[str] = None
    exchangeName: Optional[str] = None
    marginable: Optional[bool] = False
    shortable: Optional[bool] = False
    volatility: Optional[float] = None
    digits: Optional[int] = None
    field_52WkHigh: Optional[float] = Field(None, alias='52WkHigh')
    field_52WkLow: Optional[float] = Field(None, alias='52WkLow')
    peRatio: Optional[float] = None
    divAmount: Optional[float] = None
    divYield: Optional[float] = None
    divDate: Optional[str] = None
    securityStatus: Optional[str] = None
    regularMarketLastPrice: Optional[float] = None
    regularMarketLastSize: Optional[int] = None
    regularMarketNetChange: Optional[float] = None
    regularMarketTradeTimeInLong: Optional[int] = None


class EquitiesQuote(BaseModel):
    assetType: Optional[Literal['EQUITY']] = None
    symbol: Optional[str] = None
    description: Optional[str] = None
    bidPrice: Optional[float] = None
    bidSize: Optional[int] = None
    bidId: Optional[str] = None
    askPrice: Optional[float] = None
    askSize: Optional[int] = None
    askId: Optional[str] = None
    lastPrice: Optional[float] = None
    lastSize: Optional[int] = None
    lastId: Optional[str] = None
    openPrice: Optional[float] = None
    highPrice: Optional[float] = None
    lowPrice: Optional[float] = None
    closePrice: Optional[float] = None
    netChange: Optional[float] = None
    totalVolume: Optional[int] = None
    quoteTimeInLong: Optional[int] = None
    tradeTimeInLong: Optional[int] = None
    mark: Optional[float] = None
    exchange: Optional[str] = None
    exchangeName: Optional[str] = None
    marginable: Optional[bool] = False
    shortable: Optional[bool] = False
    volatility: Optional[float] = None
    digits: Optional[int] = None
    field_52WkHigh: Optional[float] = Field(None, alias='52WkHigh')
    field_52WkLow: Optional[float] = Field(None, alias='52WkLow')
    peRatio: Optional[float] = None
    divAmount: Optional[float] = None
    divYield: Optional[float] = None
    divDate: Optional[str] = None
    securityStatus: Optional[str] = None
    regularMarketLastPrice: Optional[float] = None
    regularMarketLastSize: Optional[int] = None
    regularMarketNetChange: Optional[float] = None
    regularMarketTradeTimeInLong: Optional[int] = None


class Quote(BaseModel):
    __root__: Union[
        MutualFundQuote,
        FutureQuote,
        FutureOptionQuote,
        IndexQuote,
        OptionQuote,
        ForexQuote,
        ETFQuote,
        EquitiesQuote,
    ] = Field(..., discriminator='assetType')


class GetQuoteResponse(BaseModel):
    response: Optional[Dict[str, Quote]] = None
