# generated by datamodel-codegen:
#   filename:  get_account_request.json
#   timestamp: 2023-01-01T22:45:43+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel


class Field(Enum):
    positions = 'positions'
    orders = 'orders'


class Request(BaseModel):
    fields: Optional[List[Field]] = None
    accountId: str


class Authorization(BaseModel):
    access_token: str


class GetAccountRequest(BaseModel):
    authorization: Authorization
    request: Request
