# generated by datamodel-codegen:
#   filename:  get_account_request.json
#   timestamp: 2023-01-06T20:23:23+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel

from . import authorization


class Field(str, Enum):
    positions = 'positions'
    orders = 'orders'


class GetAccountInput(BaseModel):
    fields: Optional[List[Field]] = None
    accountId: str


class GetAccountRequest(BaseModel):
    authorization: authorization.Authorization
    input: GetAccountInput
