# generated by datamodel-codegen:
#   filename:  get_quote_request.json
#   timestamp: 2023-01-01T19:23:32+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class Request(BaseModel):
    apiKey: str


class GetQuoteRequest(BaseModel):
    request: Optional[Request] = None
