# generated by datamodel-codegen:
#   filename:  get_quote_request.json
#   timestamp: 2023-01-01T22:45:44+00:00

from __future__ import annotations

from pydantic import BaseModel


class Request(BaseModel):
    apiKey: str
    symbol: str


class Authorization(BaseModel):
    access_token: str


class GetQuoteRequest(BaseModel):
    authorization: Authorization
    request: Request
