# generated by datamodel-codegen:
#   filename:  market_hours_request.json
#   timestamp: 2023-01-04T03:22:37+00:00

from __future__ import annotations

from datetime import date
from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field

from . import authorization


class Market(str, Enum):
    EQUITY = "EQUITY"
    OPTION = "OPTION"
    FUTURE = "FUTURE"
    BOND = "BOND"
    FOREX = "FOREX"


class MarketHoursInput(BaseModel):
    apiKey: str
    markets: Optional[List[Market]] = Field(None, min_items=1)
    date: Optional[date] = None


class MarketHoursRequest(BaseModel):
    authorization: authorization.Authorization
    input: MarketHoursInput
