# generated by datamodel-codegen:
#   filename:  market_hours_request.json
#   timestamp: 2023-01-04T17:36:49+00:00

from __future__ import annotations

from datetime import date
from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field

from . import authorization


class Market(str, Enum):
    EQUITY = 'EQUITY'
    OPTION = 'OPTION'
    FUTURE = 'FUTURE'
    BOND = 'BOND'
    FOREX = 'FOREX'


class MarketHoursInput(BaseModel):
    apiKey: str
    markets: List[Market] = Field(..., min_items=1)
    date: Optional[date] = None


class MarketHoursRequest(BaseModel):
    authorization: authorization.Authorization
    input: MarketHoursInput
