# generated by datamodel-codegen:
#   filename:  post_access_token_request.json
#   timestamp: 2022-12-30T22:57:21+00:00

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel
from typing_extensions import Literal


class GrantType(Enum):
    authorization_code = 'authorization_code'
    refresh_token = 'refresh_token'


class PostAccessTokenRequest(BaseModel):
    grant_type: GrantType
    refresh_token: Optional[str] = None
    access_type: Optional[Literal['offline']] = None
    code: Optional[str] = None
    redirect_uri: str
