# generated by datamodel-codegen:
#   filename:  post_access_token_response.json
#   timestamp: 2023-01-01T22:45:45+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class Response(BaseModel):
    access_token: Optional[str] = None
    refresh_token: Optional[str] = None
    token_type: Optional[str] = None
    expires_in: Optional[int] = None
    scope: Optional[str] = None
    refresh_token_expires_in: Optional[int] = None


class PostAccessTokenResponse(BaseModel):
    response: Optional[Response] = None
