# generated by datamodel-codegen:
#   filename:  user_principal_request.json
#   timestamp: 2023-01-01T22:45:45+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel


class Field(Enum):
    streamerSubscriptionKeys = 'streamerSubscriptionKeys'
    streamerConnectionInfo = 'streamerConnectionInfo'
    preferences = 'preferences'
    surrogateIds = 'surrogateIds'


class Request(BaseModel):
    fields: Optional[List[Field]] = None


class Authorization(BaseModel):
    access_token: str


class UserPrincipalRequest(BaseModel):
    authorization: Authorization
    request: Request
